Camp-SAMI/campsight

package-lock.json
server/api/amenities.js
server/api/campers.js
server/api/campgrounds.js
server/api/campsites.js
server/api/reservations.js
server/db/models/amenity.js
server/db/models/camper.js
server/db/models/campground.js
server/db/models/campsite.js
server/db/models/index.js
server/db/models/reservation.js
server/db/models/tests/amenity.spec.js
server/db/models/tests/camper.spec.js
server/db/models/tests/campground.spec.js
server/db/models/tests/campsite.spec.js
server/db/models/tests/reservation.spec.js
server/db/models/tests/user.spec.js

Models routes issue#8

---

server/auth/isAdmin.js
server/auth/isStafforAdmin.js

---
Created `isAdmin`, `isStafforAdmin` middleware to enforce Role Based Access Control.

isAdmin, isStafforAdmin middleware

---

client/store/campsite.js
client/store/campsites.js
client/store/index.js
client/store/reservation.js
client/store/reservations.js
server/api/campsites.js
server/db/models/campsite.js

Campsite reservation stores issue#15

---

campsite.md
package-lock.json
package.json
server/db/models/campsite.js

Campsite model #25

---

server/db/models/amenity.js

Update amenity model #27

---

client/components/CampsiteBlock.js
client/components/CampsiteCollection.js
client/components/index.js
client/routes.js
client/store/amenities.js
client/store/index.js
server/db/models/amenity.js
server/db/models/index.js
server/db/models/tests/amenity.spec.js
server/db/models/tests/camper.spec.js
server/db/models/tests/campground.spec.js
server/db/models/tests/campsite.spec.js
server/db/models/tests/reservation.spec.js

Campsite collection component issue#14

---

client/components/Amenities.js
client/components/NewNavbar.js
client/components/Type.js
client/components/navbar.js
package-lock.json
package.json
public/style.css

some menus done, need seed, working on new navbar

---

client/components/AdminDashboard.js
client/components/AdminSidebar.js
client/components/LandingPage.js
client/components/MapView.js

Admin sidebar #51

---

client/components/CampsiteDetail.js
client/components/Checkout.js
client/components/ReservationForm.js
package-lock.json
server/api/reservations.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, the reasoning behind the current solution, and any other relevant information for posterity.
---
Handles reservation with stripe checkout,
Handles emailing a camper upon reservation using ETHEREAL EMAIL

Campsite reservation and payment #55

---

client/components/AdminCampsites.js
client/components/MapView.js
client/store/campsites.js
client/store/index.js
client/store/ticket.js
client/store/tickets.js
package-lock.json
server/api/index.js
server/api/tickets.js

Ticket components issue#60

---

ticketSeedData.js

data to make tickets for the seed is made.

---

client/components/CampsiteBlock.js
client/components/CampsiteCollection.js
client/components/DatePicker.js
client/components/LandingPage.js
client/components/Submenu.js
client/components/navbar.js
public/style.css

---
styles are not all done..please do not delete this branch!!!!

some styles, not done

---

client/components/AddCampsite.js
client/components/AdminCampsites.js
client/components/CampsiteRow.js
client/components/ClosedTicketTable.js
client/components/EditCampsite.js
client/components/ReservationRow.js
client/store/campsite.js
server/api/campsites.js

Admin campsites issue#53

---

server/api/campers.js

unlocked routes temporarily

---

client/components/EditTicket.js
client/components/HelpSubSuccess.js
client/components/TicketForm.js
client/components/index.js

Ticket form #46

---

client/components/EditTicket.js
client/components/TicketList.js
client/components/TicketRow.js
client/components/TicketTable.js
client/components/index.js
client/store/filteredCampsites.js

Edit tickets issue#91

---

client/components/navbar.js
public/index.html
script/seed.js

Navbar fix #117

---

client/components/AdminSidebar.js
client/components/user-home.js
client/store/analiticsToggle.js
client/store/index.js

Final styles #114

---

client/components/AdminCampsites.js
client/components/Checkout.js
client/components/Itinerary.js
client/components/ReservationForm.js
client/components/TicketList.js
client/components/Type.js
script/seed.js
server/api/campers.js
server/api/reservations.js
server/db/models/reservation.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, the reasoning behind the current solution, and any other relevant information for posterity.
---
Consider carefully the commit messages if you can.

Fix calendar bugs #93

---

client/components/CamperProfile.js
client/components/CamperRow.js
client/components/user-home.js
client/store/tickets.js

routing fixes

---

client/components/AddCampsite.js
client/components/AdminSidebar.js
client/components/CamperRow.js
client/components/EditCampsite.js
client/components/TicketList.js
client/components/TicketMapView.js
client/components/TicketTable.js
client/components/index.js
client/components/user-home.js
client/routes.js
server/api/campsites.js
server/db/models/index.js

Sidebar and routes
